source 'https://github.com/fyhNB/PGPodRepo.git'

use_frameworks!

platform :ios, '13.0'

target 'Hybrid_Example' do
  pod 'Hybrid', :path => '../'

  target 'Hybrid_Tests' do
    inherit! :search_paths

    
  end
end
